### ISSUE TITLE
Backbone 0.9.9 setElement instanceof Error

### ISSUE THREAD

**Issue by danro** [amdjs/backbone#5]
Without digging too deep into this, it looks like this may have something to do with exporting Backbone globally alongside the AMD module. Tests follow:

Working `documentcloud` version:
http://jsbin.com/emakor/2/edit

Broken `amdjs` version:
http://jsbin.com/emakor/4/edit

Throws:
`Uncaught TypeError: Expecting a function in instanceof check, but got [object Object]`

What a pain. They should have kept AMD support.

**Comment by jrburke** [comment]
Oops, sorry, I goofed the merge. Fixed now and 0.9.9 tag moved accordingly.

**Comment by danro** [comment]
Thanks for the fix, James!
