### ISSUE TITLE
Backbone says Backbone.$ is undefined even though the variable is there

### ISSUE THREAD

**Issue by stefanhayden** [amdjs/backbone#6]
I'm no expert but if I use the backbone.min.js code from commit fb3bb98228e729b4653f41644f18bc56e0628768 I get this error:

Uncaught TypeError: Object #<Object> has no method '$' 

And if I use the backbone.min.js code from commit 18b445e8a0eaf438dd244121e24a2a6041c62052 then everything works fine

**Comment by jrburke** [comment]
Doh, I forgot to regenerate the min file after the last update. I did so now and moved the 0.9.9 tag to this new version.
